### ISSUE TITLE
get @watson to add all the cool places in cph

### ISSUE THREAD

**Issue by mafintosh** [diasdavid/awesome-hacking-spots#2]
resident expert

**Comment by mafintosh** [comment]
not sure if mentions work in a title so /cc @watson

**Comment by diasdavid** [comment]
sweet! Thank you @mafintosh and @watson :)

**Comment by diasdavid** [comment]
thank you for all of the great adds @watson <3. Now I'm addicted to Tartine's granola and pancakes, I've been there at least twice a week since you showed me the place and even organised a breakfast for everyone there :D
