### ISSUE TITLE
I think Tartine website link is wrong :p

### ISSUE THREAD

**Issue by FranciscoPedreira** [diasdavid/awesome-hacking-spots#27]
I think this is the right one: http://tartine.pt/

**Comment by nikolenkoanton92** [comment]
@FranciscoPedreira I am agree with you :) `Café Tati ` and `Tartine` have same webpages.

**Comment by diasdavid** [comment]
@FranciscoPedreira can you submit a PR with the fix? Thank you for catching that :)

**Comment by FranciscoPedreira** [comment]
i'd love to! but sadly i still don't know how to do it :( and i don't want to mess anything up :p (i still need to learn how to work with github - a shame i know)

**Comment by nikolenkoanton92** [comment]
I can submit a PR if you would like

**Comment by FranciscoPedreira** [comment]
Ty nikolenkoanton92!! I appreciate it :) Also i'd like to ask: there is a course in codecademy about Git. Have you or anybody else done it? If so is it worth a shot or should i look for other means to learn how to really take advantage of Git? Thanks in advance :)

**Comment by nikolenkoanton92** [comment]
@FranciscoPedreira I didn't try course in `codeacodemy` , but I hear this `https://try.github.io/levels/1/challenges/1` is very well :)

**Comment by watson** [comment]
Yes, that's the correct website - my bad ... copy/paste error ;)

**Comment by diasdavid** [comment]
@FranciscoPedreira feel free to reach out to me when I'm in Lisbon if you need a speed up, also we have a NodeSchool on the 27th where you can do the nodeschool git-it workshop :) and while you are there, get into Node.js if you haven't done so :)

Great resource to get started: https://try.github.io/levels/1/challenges/1

**Comment by FranciscoPedreira** [comment]
Ty very much @nikolenkoanton92 and @diasdavid! I will check it out for sure :)

**Comment by watson** [comment]
@diasdavid this one is fixed in master now

**Comment by diasdavid** [comment]
thank you :) 

@FranciscoPedreira also, the link to the meetup is http://www.meetup.com/require-lx/events/225709883/ :)

**Comment by FranciscoPedreira** [comment]
@diasdavid ty! i will try to attend :)
