### ISSUE TITLE
Make the README.md more editable on github.com

### ISSUE THREAD

**Issue by watson** [diasdavid/awesome-hacking-spots#29]
Currently the markdown used for tables is too wide to edit easily using the github.com editor because of linebreaks:

![screen shot 2016-01-13 at 00 03 28](https://cloud.githubusercontent.com/assets/10602/12279718/271b0ba6-b989-11e5-8c95-4d770538f763.png)

I'd propose a minimalistic style where the headers don't have to match with the content rows + merging map and address into a single location field with a link:

```markdown
Wifi | Power | Location | Open Hours
---- | ----- | -------- | ----------
✔ | ✔ | [Boldhusgade 6, 1062 København K](https://goo.gl/maps/nN7zjHsSmcU2) | Mon - Fri 7.30-17.00, Sat 11.00 - 17.00
```

which will render like so:

Wifi | Power | Location | Open Hours
---- | ----- | -------- | ----------
✔ | ✔ | [Boldhusgade 6, 1062 København K](https://goo.gl/maps/nN7zjHsSmcU2) | Mon - Fri 7.30-17.00, Sat 11.00 - 17.00

I'll make pull request if you agree :smiley:

**Comment by ralphtheninja** [comment]
+1

**Comment by diasdavid** [comment]
:+1: like it :D thank you
