### ISSUE TITLE
Organize spots by folders

### ISSUE THREAD

**Issue by aicioara** [diasdavid/awesome-hacking-spots#34]
This system is not scalable. There will be way too many merge conflicts. We should split these in files (per country / per US state). I suggest we do this now, rather than later, while there are relatively small number of PRs. 

Keep an index with references to all pages as the main README.md.

**Comment by diasdavid** [comment]
The merge conflicts have mostly been due to changes in the formatting. But I agree that with more places, we should definitely shard them by at least country for now.

**Comment by RichardLitt** [comment]
I'm not sure - this would lose the ability to see, at a glance, everything. It would also no longer conform to the awesome-list protocol developed by @sindresorhus, and I feel that is an important source of new users. 

I don't think the merge conflicts have been bad.

**Comment by aicioara** [comment]
Closing as inactive.
