### ISSUE TITLE
red rock, mountain view, ca USA

### ISSUE THREAD

**Issue by nickdesaulniers** [diasdavid/awesome-hacking-spots#42]
[map](https://www.google.com/maps/place/Red+Rock+Coffee/@37.3936357,-122.0810635,17z/data=!3m1!4b1!4m2!3m1!1s0x808fb734116ac517:0x39773b61b8c262c6)

**Comment by diasdavid** [comment]
@nickdesaulniers can you PR this?

**Comment by nikolenkoanton92** [comment]
@diasdavid we already have this one , https://github.com/diasdavid/awesome-hacking-spots#mountain-view-ca-

**Comment by diasdavid** [comment]
nice! thank you for catching that @nikolenkoanton92 :)
