### ISSUE TITLE
Add to each U.S. city state

### ISSUE THREAD

**Issue by nikolenkoanton92** [diasdavid/awesome-hacking-spots#45]
City named Bellevue, can be in different states: `Bellevue( City in Washington)` , `Bellevue (City in Ohio)` , `Bellevue ( City in Nebraska)`. I know We have state in Address, but I just think this will be better and more clean, @diasdavid  What you think about this  ? If you agree I can make PR soon.
Thanks

**Comment by diasdavid** [comment]
You mean like `Seattle, WA`? Sounds good to me @nikolenkoanton92 :)

**Comment by nikolenkoanton92** [comment]
@diasdavid  Yes :) Also, this will be better to search by state

**Comment by diasdavid** [comment]
@nikolenkoanton92 up to PR that ? :)

**Comment by nikolenkoanton92** [comment]
@diasdavid I did, just forgot to mention issue number https://github.com/diasdavid/awesome-hacking-spots/pull/44 , sorry :)

**Comment by diasdavid** [comment]
sweet! :D
