### ISSUE TITLE
Why not use existing services like WHA?

### ISSUE THREAD

**Issue by crtvhd** [diasdavid/awesome-hacking-spots#79]
e.g. submit places there? I'm not affiliated with WHA in any ways, I'm just using it for the last few months and I'm quite happy with it. Especially geolocation is a feature I wouldn't want to miss when it comes to finding places to hack.
http://workhardanywhere.com/

**Comment by RichardLitt** [comment]
So, places like that are inherently siloed, not open to collaboration (for the most part), centralized, and dependent upon adoption. 

- Siloed: The data is being held by the company. If the company website or the company goes down, the data is lost. This adds a dep that is unnecessary. It also means that the company has control of the data, and may edit it accordingly.
- Non-collaborative: You can't easily fork, request changes, or edit the document at a whim. You can suggest to the website that it change, but that raises administrative issues. A git remote doesn't have this problem.
- Centralized: The data is stored in one place. Git doesn't do this - anyone can set up a remote anywhere (including not on GitHub). 
- Adoption-necessary: Everyone has to be on board with those apps. This list is for _hackers_, which means the list should stay close to where we are - on GitHub. This keeps the list more relevant than another network. 

I also don't like WHA; their newsletter isn't relevant to my needs, and I find their company culture to be antithetical towards getting real shit done without depending on anything else. For example, they are list-prone article writers: "5 things I did that made me X" - which I find to be indicative of an unhealthy relationship between users and the actual content. 

There are dozens of working platforms. NomadList is another one. Use them - this list is for hackers on GitHub who don't want to depend on a business model to find a good cafe. 

Make sense, Martin? Let me know if I can explain this more. Also, <3.

**Comment by crtvhd** [comment]
Thanks for clarifying your opinion on this @RichardLitt. I didn't look at it form this site and to be honest I probably agree on all points you mentioned. Just found out about NomadList's placestowork.co, this looks way more interesting than WHA.
